import board

# --- PINY ---
# Feather RP2040 Prop-Maker (CP10): use board aliases available on this board
PIN_POWER = board.EXTERNAL_POWER
PIN_BUTTON = board.EXTERNAL_BUTTON
PIN_JAW_SENSE = board.D10

PIN_SERVO_LEFT = board.D11
PIN_SERVO_RIGHT = board.D12

PIN_EYES = board.D5
PIN_LED_DOME = board.TX
PIN_LED_JAW = board.RX

PIN_LASER_SDA = board.SDA
PIN_LASER_SCL = board.SCL

# --- SERWA ---
S1_OPEN = 160
S1_CLOSE = 20
S2_OPEN = 20
S2_CLOSE = 160

OPEN_REDUCTION_DEG = 2

SERVO_MAX_SPEED_DPS = 78.0
SERVO_OPEN_SPEED_MULT = 1.35
SERVO_CLOSE_SPEED_MULT = 1.0
SERVO_OPEN_FAST_EASE = True
SERVO_UPDATE_DELAY = 0.012
SERVO_SETTLE_TIME = 0.12
SERVO_RELEASE_AFTER_CLOSE = True
SERVO_RELEASE_DELAY = 0.20

SERVO_MIN_ANGLE = 0
SERVO_MAX_ANGLE = 180
SERVO_MIN_PULSE = 750
SERVO_MAX_PULSE = 2250

# --- LASER ---
LASER_DIST_LIMIT = 250
LASER_MIN_VALID_MM = 40
LASER_DEBOUNCE = 3
LASER_HOLD_TIME = 0.35
LASER_FILTER_ALPHA = 0.40
LASER_TIMING_BUDGET_US = 50000

# --- OGOLNE ---
ANIMATION_MODE = 1
AUTO_CLOSE_DELAY = 5.0
EYE_MAX_BRIGHT = 1.0
LED_UPDATE_DELAY = 0.03

BUTTON_DEBOUNCE = 0.06
BUTTON_COOLDOWN = 2.0
MULTI_CLICK_WINDOW = 0.55
SINGLE_CLICK_DECISION_DELAY = 0.30
TRIPLE_CLICK_COUNT = 3
DEMO_FX_DURATION = 4.0
BUTTON_USE_KEYPAD_EVENTS = False
SERVO_PAIR_SUM = 180
START_OPEN = False

JAW_SENSE_ENABLED = False
JAW_DETACH_ACTIVE_LEVEL = False
JAW_DETACH_DEBOUNCE = 0.60

RUNTIME_DIAG_ENABLED = True
RUNTIME_DIAG_INTERVAL = 2.0

NUM_LEDS_DOME = 15
NUM_LEDS_JAW = 8

SND_STARTUP = "startup.wav"
SND_OPEN = "open.wav"
SND_CLOSE = "close.wav"

SHOW_OFF_ENABLED = False
SHOW_OFF_INTERVAL = 10.0

# --- DEMO SEQUENCE (DLUGI TRYB POKAZOWY) ---
DEMO_SEQUENCE_ENABLED = True
DEMO_STAGE_IGNITION = 1.8
DEMO_STAGE_OPEN_HOLD = 2.8
DEMO_STAGE_CLOSE_HOLD = 2.2
DEMO_STAGE_ARC = 2.4
DEMO_STAGE_FINAL_HOLD = 2.6
DEMO_EYE_PULSE_MIN = 0.08
